add snarkyjs-pack community package to README.md
o1-labs/o1js pull request #1040
Opened 2023-07-20 19:35 UTC by barriebyron

This PR adds our second community package for SnarkyJS to the README 

https://discord.com/channels/484437221055922177/915745847692636181/1131617947534753962

2023-07-20 23:46 UTC, ymekuria approved these changes
Exciting to see more community packages!

2023-07-21 10:57 UTC, mitschabaude requested changes
Just making sure -- someone review the library?

2023-07-23 07:35 UTC, Trivo25 commented
I just took a quick look. It would be good if the package could add an e2e integration test (demonstrating the functionality in a smart contract, or other provable code). Additionally, I couldn't find any doc comments (which would be a nice to have!) cc @45930

2023-07-23 14:49 UTC, 45930 commented
@Trivo25 yeah I will plan to do that after my cohort 1 presentation.  I am busy working on that for the next couple weeks.

2023-07-23 14:51 UTC, 45930 commented
@mitschabaude no one has reviewed thoroughly AFAIK

2023-07-24 05:13 UTC, Trivo25 commented
> @Trivo25 yeah I will plan to do that after my cohort 1 presentation. I am busy working on that for the next couple weeks.

That's fine! It's not a must, but would be great *if* you want to be listed as a community package in SnarkyJS :)

2023-07-25 19:10 UTC, mitschabaude approved these changes

2023-07-26 15:21 UTC, barriebyron commented
@mitschabaude I see you approved, because I am uncertain about the technical status, would you be up for merging this PR when you feel the package meets the high quality package guidelines? Another option, we label it as experimental?

2023-07-26 16:09 UTC, mitschabaude commented
> @mitschabaude I see you approved, because I am uncertain about the technical status, would you be up for merging this PR when you feel the package meets the high quality package guidelines? Another option, we label it as experimental?

I only approved to no longer be "requesting changes" 😅 I think the comment by Florian still makes sense, we want those packages to have a test

2023-07-28 14:32 UTC, barriebyron commented
Excited about our second package candidate. We'll leave this PR open as we await package updates from @45930

2023-09-19 04:59 UTC, 45930 commented
Hi guys.  I added provable tests and doc comments, as well as rebranded everything to "o1js".

https://github.com/45930/o1js-pack/blob/main/src/lib/PackingPlant.ts
https://github.com/45930/o1js-pack/blob/main/tests/provable/end_to_end.test.ts

2023-09-19 16:16 UTC, barriebyron commented
ready to merge, thank you @45930 for your contribution and community package 

I contributed https://github.com/45930/o1js-pack/pull/14

2023-09-19 16:24 UTC, barriebyron commented on README.md
> +- **snarkyjs-pack** A library for SnarkyJS that allows a zkApp developer to pack extra data into a single Field. [GitHub](https://github.com/45930/o1js-pack) and [npm](https://www.npmjs.com/package/o
```suggestion
- **o1js-pack** A library for o1js that allows a zkApp developer to pack extra data into a single Field. [GitHub](https://github.com/45930/o1js-pack) and [npm](https://www.npmjs.com/package/o1js-pack)
```

2023-09-19 18:32 UTC, merged