Add Base64 Encoding/Decoding and Enhanced String Handling for Bytes
o1-labs/o1js pull request #1659
Opened 2024-05-18 10:10 UTC by Shigoto-dev19

## Description

All changes revolve around the provable **Bytes** class.

## Changes

- Added `base64Encode` and `base64Decode` methods.
- Added unit tests for the new Base64 methods.
- Updated `toHex()` method to `toString()` with improved support for various encodings.
  - Utilized `Buffer.from(this.toBytes()).toString(encoding, start, end)` to allow converting Bytes to string with different encodings and optional byte range selection.
- Similarly, updated `fromString(s)` to support more encodings, aligned with the native `BufferEncoding` union type.

### Notes

- For detailed instructions on using Base64 encode/decode in o1js and an overview of provable Base64 constraints, refer to the `o1js-base64` [repo README](https://github.com/Shigoto-dev19/o1js-base64?tab=readme-ov-file#o1js-base64-encodedecode).
- For an example of zkPrograms using Base64, see this [file](https://github.com/Shigoto-dev19/o1js-base64/blob/main/src/run.ts).

2024-05-18 11:36 UTC, mitschabaude requested changes
Thanks @Shigoto-dev19! This is an incredible addition to o1js.

I'll review in detail later but have some quick feedback: You can't remove methods like `toHex()` and `fromHex()` because this is a breaking change and would move o1js to version 2.0 according to semver, which we don't want.

2024-05-20 10:06 UTC, mitschabaude reviewed
I reviewed it, have a few more comments, looks great overall

2024-05-20 10:07 UTC, mitschabaude commented
note that the tests are just failing because you changed the `bindings` and `mina` submodules

2024-05-20 10:28 UTC, Shigoto-dev19 commented
> I reviewed it, have a few more comments, looks great overall

Thank you for the review! I'll address the comments and update the branch :)

2024-05-21 20:44 UTC, Shigoto-dev19 commented on src/lib/provable/bytes.ts
> +function base64DLookup(input: UInt8): Field {
I agree!

2024-05-21 20:54 UTC, Shigoto-dev19 commented on src/lib/provable/bytes.ts
> +    let decodedB64Bytes: UInt8[] = [];
Awesome catch!

2024-05-21 21:13 UTC, Shigoto-dev19 commented on CHANGELOG.md
> +- Changed fromString(s) to support more encodings, aligned with the native BufferEncoding union type.
I removed the changed subsection as `Buffer` is no longer used.

2024-05-21 21:14 UTC, Shigoto-dev19 commented on CHANGELOG.md
> +- Added `toString(encoding?: BufferEncoding, start?: number, end?: number)` method for converting Bytes to string with different encodings and optional byte range selection.
I deleted the `Bytes.toString()` both as a method and in changelog

2024-05-22 05:54 UTC, mitschabaude approved these changes

2024-05-22 08:26 UTC, merged